services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/db/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 5
  web:
    build:
      context: .
    container_name: superbank
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata wallet.json &&
             python manage.py loaddata transaction.json &&
             python manage.py loaddata user.json &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    volumes:
      - ./superbank:/superbank
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
